# Meta Data for SEO

## Homepage
title = "eu1"
titleSeparator = "-"
titleAddition = "Email & Messaging Service"
description = ""

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "doks.netlify.app"
titleHome = "Doks Theme"

## Twitter Cards
twitterSite = "@getdoks"
twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "eu1"
schemaAuthor = "bh90210"
schemaAuthorTwitter = ""
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = "https://github.com/euoe"
schemaLocale = "en-US"
schemaLogo = "eu1.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "eu1.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/euoe/eu1"
schemaSection = "docs"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Consider supporting us bitcoin:bc1qvf7pp3gx3r3wue4kar70sdny8egu73y379gsk6"
copyRight = "2021 euoe"

# Alert
alert = false
alertText = "Like eu1? <a class=\"alert-link\" href=\"https://github.com/euoe/eu1/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/euoe/euoe"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  collapsibleSidebar = false
